#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if [[ $(uname) == 'Darwin' && -x /opt/homebrew/bin/brew ]]; then
  # Homebrew
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# "$HOME/.cargo/env"が存在すれば実行する
test -f "$HOME/.cargo/env" && source "$HOME/.cargo/env"
