# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Add /opt/homebrew/bin to path
export PATH=/opt/homebrew/bin:$PATH
# Add nodebrew to path
export PATH=$HOME/.nodebrew/current/bin:$PATH

alias "?s"="gh copilot suggest"
alias "?e"="gh copilot explain"

# Add fzf(fuzzy finder) to path
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit && compinit -i

alias fzfv='fzf --preview "bat  --color=always --style=header,grid --line-range :100\
 {}"'

# sshを実行したあとにechoを実行する関数を定義
function ssh() {
  echo -e "\033]50;SetProfile=$1\a"
  command ssh "$@"
  echo -e "\033]50;SetProfile=Default\a"
}
